#!/usr/bin/env python3
#
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#


NOISY_LOCATIONS = [
    "adr",
    "adriatic",
    "adriatic sea",
    "aeg",
    "aegean",
    "aegean sea",
    "alb",
    "albania",
    "ank",
    "ankara",
    "apu",
    "apulia",
    "arm",
    "bal",
    "baltic",
    "baltic sea",
    "bar",
    "barents",
    "barents sea",
    "bel",
    "belg",
    "belgium",
    "ber",
    "berlin",
    "bla",
    "black",
    "black sea",
    "boh",
    "bohemia",
    "bot",
    "bothnia",
    "bre",
    "brest",
    "bud",
    "buda",
    "budapest",
    "bul",
    "bulg",
    "bulgaria",
    "bur",
    "burgundy",
    "cly",
    "clyde",
    "con",
    "const",
    "constantinople",
    "den",
    "denmark",
    "eas",
    "eastmed",
    "ec",
    "ech",
    "edi",
    "edinburgh",
    "eme",
    "emed",
    "ems",
    "eng",
    "english channel",
    "fin",
    "gal",
    "galacia",
    "galicia",
    "gas",
    "gascony",
    "gob",
    "gol",
    "gre",
    "greece",
    "gulf of bothnia",
    "gulf of lyon",
    "gulf of lyons",
    "gulfofb",
    "gulfofl",
    "hel",
    "helgoland",
    "hol",
    "ion",
    "ion sea",
    "ionian",
    "ionian sea",
    "iri",
    "irish",
    "irish sea",
    "keil",
    "kie",
    "kiel",
    "liverpool",
    "livo",
    "livonia",
    "livp",
    "lon",
    "london",
    "lpl",
    "lva",
    "lvn",
    "lvo",
    "lvp",
    "lyo",
    "lyon",
    "mao",
    "mar",
    "mars",
    "marseille",
    "marseilles",
    "mat",
    "mid",
    "mid atl",
    "mid atlantic",
    "midatlantic",
    "mos",
    "moscow",
    "mun",
    "munich",
    "naf",
    "nao",
    "nap",
    "naples",
    "napoli",
    "nat",
    "nor",
    "nora",
    "norsea",
    "norw",
    "norwegian",
    "norwsea",
    "nrg",
    "ns",
    "nth",
    "nts",
    "nwg",
    "nwy",
    "par",
    "paris",
    "pic",
    "picardy",
    "pie",
    "pied",
    "piedmond",
    "piedmont",
    "piemonte",
    "por",
    "pru",
    "prussia",
    "rom",
    "roma",
    "romania",
    "ruh",
    "ruhr",
    "rum",
    "rumania",
    "ser",
    "serb",
    "serbia",
    "sev",
    "seva",
    "sevastapol",
    "sevastopol",
    "sil",
    "silesia",
    "ska",
    "skag",
    "skagerrack",
    "skagerrak",
    "smy",
    "smyrna",
    "spa",
    "spain",
    "st pete",
    "st petersburg",
    "st petes",
    "st. pete",
    "st. petersburg",
    "st. petes",
    "stp",
    "swe",
    "sweden",
    "sweeden",
    "swi",
    "switz",
    "syr",
    "the adriatic",
    "the aegean",
    "the aegean sea",
    "the baltic",
    "the baltic sea",
    "the black sea",
    "the channel",
    "the english channel",
    "the ionian",
    "the ionian sea",
    "the irish sea",
    "the mao",
    "the mid-atlantic",
    "the mid-atlantic ocean",
    "the ukraine",
    "tri",
    "triest",
    "trieste",
    "trl",
    "tun",
    "tunis",
    "tunisia",
    "tus",
    "tuscany",
    "tyh",
    "tyl",
    "tyn",
    "tyr",
    "tyr sea",
    "tyrolia",
    "tyrr",
    "tyrr sea",
    "tyrrhenian",
    "tyrrhenian sea",
    "tys",
    "ukr",
    "ukraine",
    "ven",
    "venice",
    "venizia",
    "vie",
    "vien",
    "viena",
    "vienna",
    "wal",
    "wales",
    "war",
    "warsaw",
    "wm",
    "wme",
    "wmed",
    "wms",
    "yonkers",
    "yor",
    "york",
]
